navn = input("Skriv ditt navn\n")
print("Hei", navn, "hvor gammel er du?")
alder = int(input())
progalder = int(input("Hvor gammel var du da du begynte å programmere?\n"))
differanse = (int(alder)-int(progalder))
print("Da har du programmert i", differanse, "år.")
print("Syns du de", differanse, "årene har vært givende?")
input()
print("takk for svar,", navn)
