print("Vennligst gi inn et flyttall med med minst 5 siffer både før og etter .")
starttall = float(input("Hva er tallet ditt\n"))
inttall = int(starttall)
print("Konvertert til heltall med int():", inttall)
print("Avrundet til nærmeste heltall:", round(starttall))
print("Avrundet til to desimaler:", round(starttall, 2))
print("Avrundet til fire desimaler:", round(starttall, 4))
print("Avrundet til nærmeste tusen:", inttall//1000*1000)
print("Heltall fra int() konvertert tilbake til flyttall", float(inttall))
